services:
  backend:
    environment:
      - NODE_ENV=development
    ports:
      - "${HOST_IP:-0.0.0.0}:3000:3000"
    
  frontend:
    build:
      context: ./Frontend/front
      dockerfile: Dockerfile
      args:
        - BACKEND_HOST=${HOST_IP:-localhost}
        - BACKEND_PORT=3000
    ports:
      - "${HOST_IP:-0.0.0.0}:4200:80"
