
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PM2_PUBLIC_KEY=${PM2_PUBLIC_KEY:-}
      - PM2_SECRET_KEY=${PM2_SECRET_KEY:-}
    volumes:
      - ./Backend/prisma:/app/prisma
      - ./Backend/assets:/app/assets
      - backend_data:/app/data
      - backend_logs:/app/logs
    networks:
      - simple-menu-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./Frontend/front
      dockerfile: Dockerfile
      args:
        - BACKEND_HOST=backend
        - BACKEND_PORT=3000
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production
      - NGINX_WORKER_PROCESSES=auto
      - NGINX_WORKER_CONNECTIONS=1024
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - simple-menu-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  backend_data:
  backend_logs:

networks:
  simple-menu-network:
    driver: bridge
